### ISSUE TITLE
Demo refernced in the description is broken

### ISSUE THREAD

**Issue by kristoffernolgren** [agrublev/angularLocalStorage#31]
http://plnkr.co/edit/Y1mrNVRkInCItqvZXtto?p=preview

console:
POST http://run.plnkr.co/E1AltyBNNZWYRWaL/ 400 (Bad Request) 
POST http://run.plnkr.co/E1AltyBNNZWYRWaL/ 400 (Bad Request)

**Comment by hppycoder** [comment]
This has been corrected today, there is now a new Plunker with a working example using ngRepeat and binding. Thanks!
