### ISSUE TITLE
get method using jquery cookie

### ISSUE THREAD

**Issue by thombrg** [agrublev/angularLocalStorage#39]
the get method implementation in (!support) if branch is using jquery cookie when perhaps it should be using angular cookieStore.

recommend change 
return privateMethods.parseValue($.cookie(key));
to
return privateMethods.parseValue($cookieStore.get(key));

**Comment by hppycoder** [comment]
@agrublev I believe this is corrected already? If so please close the issue. I don't see any jQuery being used any longer.

**Comment by voronianski** [comment]
@agrublev @hppycoder if you need a cookie fallback then just pick ngKookies - https://github.com/voronianski/ngKookies

**Comment by voronianski** [comment]
@hppycoder and where did you see jquery cookie in `get` method? - https://github.com/agrublev/angularLocalStorage/blob/master/src/angularLocalStorage.js#L91
