### ISSUE TITLE
Ng-repeat error because of dupes.

### ISSUE THREAD

**Issue by adalberth** [agrublev/angularLocalStorage#54]
Fix: change "var saver = $window.json.." to:
var saver = $window.JSON.stringify(value, function (key, val) {
    if (key == '$$hashKey') {
        return undefined;
    }
    return val;
});

**Comment by hppycoder** [comment]
Closing as duplicate of #41 

Thank you for finding the same thing, will get this into a PR shortly. Once a simple sample has been setup and it can be tested!
