### ISSUE TITLE
Private Browsing in Safari Breaks

### ISSUE THREAD

**Issue by neekers** [agrublev/angularLocalStorage#59]
When I try to use localStorage on Safari while private browsing I get an error that I cannot catch.

Cookie 'config' possibly not set or overflowed because it was too large (1018591 > 4096 bytes)!

Looks like the fallback to the $cookieStore isn't throwing an error I can catch and swallow. If I can't store it, then I don't want my app to crash.

**Comment by hppycoder** [comment]
@neekers  - Can you please test master to see if this still occurs? I am unable to recreate your issue given my setup here.

**Comment by skattabrain** [comment]
Any plans on getting this working? Your bind functionality is simply awesome and don't want to retrofit my app to a different solution.

But I can confirm... private browsing on iOS doesn't work.

**Comment by CamaroSS** [comment]
@skattabrain , do you confirm it on the latest release? Do you have angular-cookies loaded?

**Comment by skattabrain** [comment]
I do load it in ngCookies in my module... do I need to load $cookies or $cookieStore in my controller?

**Comment by skattabrain** [comment]
Denis, sorry for the firedrill. Looks like I was thrown off by a few things at the same time. For some reason, when in private mode it did not like the way i was checking if my binded variable was defined. I use angular.isDefined and it works fine.

Odd that it was only throwing an exception in private mode... but regardless... works in private mode now.

Thanks guys!
