### ISSUE TITLE
GitHub Release 0.3.0

### ISSUE THREAD

**Issue by hppycoder** [agrublev/angularLocalStorage#63]
Please release officially 0.3.0, to denote the change in the bower.json file.

**Comment by agrublev** [comment]
Please add a pull request, or I  can add you as a contributor if you'd like.

**Comment by hppycoder** [comment]
@agrublev - I would like to become a contributor if you would grant me permission. I really like this project and have been using it for some time. One of my latest projects will be using this in Angular 1.3.

**Comment by karser** [comment]
+1

**Comment by agrublev** [comment]
Done and Done!!!

**Comment by hppycoder** [comment]
Thanks
