### ISSUE TITLE
The components folder should be removed

### ISSUE THREAD

**Issue by panuhorsmalahti** [agrublev/angularLocalStorage#68]
I think this folder should be removed. The examples could reference a public angularjs cdn, or the dependencies could be fetch using bower for the example.

Reason for removing: it wastes space and increases maintenance.

**Comment by hppycoder** [comment]
Agreed, remove that and put the components folder into the .gitignore so it doesn't happen again.

**Comment by hppycoder** [comment]
Finished, removed the folder and then had to implement a hook into travis to run ```bower install``` first before it executed anymore scripts.

**Comment by hppycoder** [comment]
Thanks for the suggestion, got this closed up.
