### ISSUE TITLE
Dep on angular-cookie missing

### ISSUE THREAD

**Issue by Ryuno-Ki** [agrublev/angularLocalStorage#70]
In case you are not downloading https://github.com/ivpusic/angular-cookie (for example via bower) loading storage throws an error from angular.

Hence, add it as dependency (I downloaded this repo via bower).

**Comment by panuhorsmalahti** [comment]
That doesn't seem correct. angularLocalStorage depends on "angular-cookies": "~1.3.0", which is defined in bower.json. The readme also states '(REMEMBER to add angular-cookies.min.js script to your project'.

**Comment by Ryuno-Ki** [comment]
Okay, I can confirm your point.

Would you wrap the remember in strong-tags?
