### ISSUE TITLE
CDN missing

### ISSUE THREAD

**Issue by Ryuno-Ki** [agrublev/angularLocalStorage#71]
Why does this cool repo not have a CDN?

Could you ask at https://cdnjs.com/ for one?

**Comment by panuhorsmalahti** [comment]
Feel free to add this to cdnjs, instructions can be found here:
https://github.com/cdnjs/cdnjs

**Comment by Ryuno-Ki** [comment]
Would be handy, if you could add a version number to package.json then.

Remember to [use](http://git-scm.com/book/en/v2/Git-Basics-Tagging) `git tag` for the commits, to.

Oh, and we need a minified flavour of your js file :)

I will take care for the rest, then.

**Comment by panuhorsmalahti** [comment]
Added a version number to package.json.

**Comment by panuhorsmalahti** [comment]
Added a minifed javascript file to the dist folder and changed the main property to point to it.

**Comment by panuhorsmalahti** [comment]
I think someone should bump the version, tag it and release it to npm and bower.

**Comment by Ryuno-Ki** [comment]
PR against cdnjs: https://github.com/cdnjs/cdnjs/pull/4456

**Comment by Ryuno-Ki** [comment]
Mentioned PR was accepted and I verified it.
Hence closing.
